### ISSUE TITLE
Game crash at the end for party

### ISSUE THREAD

**Issue by jewome62** [lmk02/BlockParty#26]
**Describe the bug**
The players has been playe a game.
Their return to the spawn lobby (with sign)
And their can't replay, the game say "The game you are trying to join is already running"

**To Reproduce**
I don't know how reproduce

**Screenshots**
Log : https://pastebin.com/JWVwL2TW
![image](https://user-images.githubusercontent.com/472429/77860686-bfbb7c80-7210-11ea-8c55-5c5c689d66f5.png)

**Environment):**
 - Server version: Paper 1.13.2
 - BlockParty version 2.0.3.4-REALEASE

**Additional context**

**Comment by jewome62** [comment]
I have reproduce, the crash come when player disconnect from the server during the party

**Comment by Leon167** [comment]
Thank you for submitting all the bugs and feature requests. Bugs will be fixed in the next build.

**Comment by jewome62** [comment]
Any news ? i must restart my server every hour because that's :(

**Comment by Leon167** [comment]
I am really sorry. Trying my best to fix it
