### ISSUE TITLE
1.16 support. Just compile and release ?

### ISSUE THREAD

**Issue by jewome62** [lmk02/BlockParty#37]
Hello

i see the PR #35 byb @syldium it was merged.
It's possible to have compiled Jar ? I try with mvn to compile but that's not working and i not Java Expert

thanks

**Comment by syldium** [comment]
Hello there, I don't know if a release is planned, but you can get a build of the master branch on my [fork](https://github.com/syldium/BlockParty/releases/tag/v2.0.4-ALPHA).
