### ISSUE TITLE
Permission don't work !

### ISSUE THREAD

**Issue by CodesGamesYTB** [lmk02/BlockParty#41]
I'm trying to give "blockparty.user. *" Permission through the "GroupManager" plugin, but players still don't have permission.

Minecraft version: Vanilla 1.12.2
Plugin version: BlockParty 2.0.3.4

**Comment by syldium** [comment]
Hello,

Your permission plugin strictly interprets wildcard permissions. Since the permissions of the BlockParty plugin are not predefined, GroupManager is unable to interpret this permission node. You could set the permissions manually or use a compatible plugin such as LuckPerms.
