### ISSUE TITLE
Bug after GameStart.

### ISSUE THREAD

**Issue by Maximilian1021** [lmk02/BlockParty#47]
**Describe the bug**
When the round starts. Spawn events (beacons) throughout and the floor makes fat party... See video

**To Reproduce**
After Start a Round

**Expected behavior**

That the round starts normally... ...

**Screenshots**
Youtube Video:
https://youtu.be/aznPBVDLjjE

Latest.log
https://haste.max1021.de/oyudidupor.properties

**Environment):**
 - Server version: Paper 1.16.5
 - BlockParty version  2.0.3.5-ALPHA
 - Additional Plugins SimpleCloud Plugins (Cloud System)

**Additional context**
For a demonstration please contact Maximilian1021

**Comment by phm07** [comment]
Install the latest release from https://github.com/lmk02/BlockParty/releases/tag/2.0.5-RELEASE and check if the issue still persists.

**Comment by Maximilian1021** [comment]
The now current release works on the 1.16.5 now without errors and problems as far as I can see it. The round starts normally.

Thanks for the quick solution
